# REINVENT4 Configuration for Pocket-Based Drug Design
# Production-ready configuration with stable convergence

run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_logs"
json_out_config = "_pocket_rl.json"

[parameters]
prior_file = "data/priors/reinvent.prior"
agent_file = "data/priors/reinvent.prior"
summary_csv_prefix = "pocket_results"
use_checkpoint = false
purge_memories = false

# Small batch size to prevent timeout
batch_size = 10
unique_sequences = true
randomize_smiles = true

[learning_strategy]
type = "dap"
sigma = 128
# Conservative learning rate for stability
rate = 0.00005

[diversity_filter]
type = "IdenticalMurckoScaffold"
bucket_size = 50
minscore = 0.2

# Stage 1: Exploration with balanced scoring
[[stage]]
chkpt_file = 'exploration.chkpt'
termination = "simple"
max_score = 0.8
min_steps = 50
max_steps = 1000

[stage.scoring]
type = "arithmetic_mean"

# Drug-likeness (QED)
[[stage.scoring.component]]
[stage.scoring.component.Qed]
[[stage.scoring.component.Qed.endpoint]]
name = "QED"
weight = 0.3

# AutoDock Vina docking score
[[stage.scoring.component]]
[stage.scoring.component.external_process]
[[stage.scoring.component.external_process.endpoint]]
name = "Vina_Docking"
weight = 0.4
params.executable = "/fs/ess/PAA0203/xing244/.conda/envs/reinvent4/bin/python"
params.args = "/fs/ess/PAA0203/xing244/temp_modelling/generative_model_test/pocket_final_test/reinvent_vina_interface.py"

# Molecular Weight constraint (250-450 Da)
[[stage.scoring.component]]
[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MW"
weight = 0.2

transform.type = "double_sigmoid"
transform.high = 450.0
transform.low = 250.0
transform.coef_div = 100.0
transform.coef_si = 50.0
transform.coef_se = 50.0

# LogP constraint (1-4)
[[stage.scoring.component]]
[stage.scoring.component.SlogP]
[[stage.scoring.component.SlogP.endpoint]]
name = "LogP"
weight = 0.1

transform.type = "double_sigmoid"
transform.high = 4.0
transform.low = 1.0
transform.coef_div = 1.5
transform.coef_si = 50.0
transform.coef_se = 50.0

# Stage 2: Focused optimization
[[stage]]
chkpt_file = 'optimization.chkpt'
termination = "simple"
max_score = 0.85
min_steps = 30
max_steps = 80

[stage.scoring]
type = "arithmetic_mean"

# Higher QED weight in stage 2
[[stage.scoring.component]]
[stage.scoring.component.Qed]
[[stage.scoring.component.Qed.endpoint]]
name = "QED"
weight = 0.3

# Higher docking weight
#[[stage.scoring.component]]
#[stage.scoring.component.external_process]
#[[stage.scoring.component.external_process.endpoint]]
#name = "Vina_Docking"
#weight = 0.5
#params.executable = "/fs/ess/PAA0203/xing244/.conda/envs/reinvent4/bin/python"
#params.args = "/fs/ess/PAA0203/xing244/temp_modelling/generative_model_test/pocket_final_test/reinvent_vina_interface.py"

# Tighter MW constraint
[[stage.scoring.component]]
[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MW"
weight = 0.2

transform.type = "double_sigmoid"
transform.high = 400.0
transform.low = 300.0
transform.coef_div = 50.0
transform.coef_si = 80.0
transform.coef_se = 80.0